CREATE DATABASE IF NOT EXISTS rewardMe;

USE rewardMe;

-- Main tables

-- Customisation tables
CREATE TABLE IF NOT EXISTS Position (
	PositionID INTEGER NOT NULL AUTO_INCREMENT,
	xCords DECIMAL(6, 2) NOT NULL,
	yCords DECIMAL(6, 2) NOT NULL, 
	rotation INTEGER NOT NULL,
	sizePx INTEGER NOT NULL,
	PRIMARY KEY (PositionID)
);

CREATE TABLE IF NOT EXISTS Style (
	StyleID INTEGER NOT NULL AUTO_INCREMENT,
	showDate BOOLEAN NOT NULL, 
	borderColour INTEGER NOT NULL,
	backgroundColor INTEGER NOT NULL,
	PRIMARY KEY (StyleID)
);


CREATE TABLE IF NOT EXISTS User(
	UserID INTEGER NOT NULL AUTO_INCREMENT,
	firstName VARCHAR(64) NOT NULL,
	lastName VARCHAR(64) NOT NULL,
	email VARCHAR(128) NOT NULL,
	passwordHash VARCHAR(256) NOT NULL, 
	profilePicID INTEGER, 
	PRIMARY KEY (UserID)
);

CREATE TABLE IF NOT EXISTS Job(
	JobID INTEGER NOT NULL AUTO_INCREMENT,
	heading TEXT NOT NULL,
	description TEXT,
	dateCreated DATETIME NOT NULL,
	dateDeadline DATETIME,
	completed BOOLEAN NOT NULL,
	PositionID INTEGER NOT NULL,
	StyleID INTEGER NOT NULL, 
	PRIMARY KEY (JobID),
	FOREIGN KEY (PositionID) REFERENCES Position (PositionID), 
	FOREIGN KEY (StyleID) REFERENCES Style (StyleID)
);

CREATE TABLE IF NOT EXISTS Task (
	TaskID INTEGER NOT NULL AUTO_INCREMENT, 
	heading TEXT NOT NULL,
	description TEXT,
	dateCreated DATETIME NOT NULL,
	dateDeadline DATETIME, 
	completed BOOLEAN NOT NULL, 
	PositionID INTEGER NOT NULL, 
	StyleID INTEGER NOT NULL,
	PRIMARY KEY (TaskID),
	FOREIGN KEY (PositionID) REFERENCES Position (PositionID), 
	FOREIGN KEY (StyleID) REFERENCES Style (StyleID)
);

-- Connection tables
CREATE TABLE IF NOT EXISTS User_Jobs (
	UserID INTEGER NOT NULL,
	JobID INTEGER NOT NULL,
	PRIMARY KEY (UserID, JobID),
	FOREIGN KEY (UserID) REFERENCES User (UserID),
	FOREIGN KEY (JobID) REFERENCES Job (JobID)
);

CREATE TABLE IF NOT EXISTS Job_Tasks (
	JobID INTEGER NOT NULL, 
	TaskID INTEGER NOT NULL, 
	PRIMARY KEY (JobID, TaskID),
	FOREIGN KEY (TaskID) REFERENCES Task (TaskID),
	FOREIGN KEY (JobID) REFERENCES Job (JobID)
);

